openapi: 3.0.3

info:
    title: LMS API
    description: API cho hệ thống quản lý học tập
    version: 1.0.0

servers:
    - url: /api/v1

paths:
    /auth/login:
        post:
            summary: Đăng nhập
            tags:
                - Tài khoản
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/LoginRequest"

            responses:
                "200":
                    description: Đăng nhập thành công
                "401":
                    description: Sai username hoặc password

components:
    schemas:
        LoginRequest:
            type: object
            required:
                - username
                - password
            properties:
                username:
                    type: string
                    example: "sieunhandienquang@sis.hust.edu.vn"

                password:
                    type: string
                    example: "123456"
